### ISSUE TITLE
Сделаем ларапизза великим опять!!1

### ISSUE THREAD

**Issue by solbianca** [DynamicSTOP/larapizza#1]
**Нет тестов**. Код обязательно надо покрыть хотя бы юнит тестами. 

**Контроллеры.** Надо выделить логику из контроллеров. Даже сейчас они начинают выглядеть немного перегруженными.

Можно вынести валидацию в отдельные сущности: 

https://laravel.com/docs/7.x/validation#form-request-validation

Плюс такого подхода в том что теперь не надо думать о данных. Если данные попали в контроллер, значит они валидны и с ними можно спокойно работать. 

Мы не должны ходить в базу внутри контроллеров: 

https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Http/Controllers/UserController.php#L13

По хорошему нам необходимо выделить OrderProvider. Его задача предоставлять корзину для пользователя. Например его интерфейс мог выглядеть как то так:

> interface OrderProvider {
> 	provideByUserId(int $userId) Cart;
> }

И уже внутри провайдеры мы собираем корзину с товарами. И везде, где нам нужна корзина, мы бы ходили в этот провайдер. Допустим у нас есть несколько мест где может выводится корзина - страница корзины, страница промо акции, попап который открывается по нажатию на значок корзины. Допустим бизнес решил устроить акцию и на все заказы сделал скидку 5%. Теперь нам надо поменять код только в провайдере, а не искать все места где мы собираем корзину пользователю.  

Еще важный момент. Модель Cart описывает то как наши данные лежат в базе. Но это не ложится на ожидаемое представление данных для пользователя. Поэтому имеет смысл создать отдельную сущность для описания корзины для пользователя. Это позволит более гибко и безопасно работать как с AR моделью, так и с моделью приложения.

**Используй инъекции зависимостей.** Фасады в ларавеле это конечно удобно, и на них даже можно при желании написать тест. Но каждый такой фасад это неявная зависимость. А это плохо. Они быстро разрастаются. Легко потерять контроль за тем сколько и как часто ты дергаешь за фасад. И это может стать проблемой.

**Надо разделять методы на отдельные действия.** Вот тут брошены грабли. Это лишь вопрос времени когда об них сломают ноги.
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Http/Controllers/CartController.php#L33

**Валюты.** В коде довольно много работаем с валютой. И код выглядит так:
$currency === ‘euro’

Допустим, завтра добавится валюта канадский доллар. И вот у нас тысяча мест где мы должны внести правки. И где то мы конечно же забудем. И будем еще долго закрывать задачи с багофиксами. По хорошему мы должны работать с константами. Например, мы бы могли выделить отдельный словарь валют: https://en.rmcreative.ru/blog/moving-constants-into-dictionaries/

В котором бы в том числе инкапсулировали логику работы с валютой. Таким образом мы работаем не со строками а с константами. У нас единая точка доступа/описания валют. В будущем можно будет гораздо проще вносить изменения в код.

**Код в едином стиле.** Весь код должен быть в едином стиле. Если код пишется в camel case то он змеек быть не должно:
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Http/Controllers/CheckoutController.php#L25

**Мертвый код.** По коду часто встречаются пустые комментарии. В них нет никакого смысла. Их надо удалить.

https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Cart.php#L10
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Goods.php#L10
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Order.php#L9
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/OrderItem.php#L9
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/database/seeds/GoodsSeeder.php#L14
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Console/Kernel.php#L16

Закомментированный код = мертвый код. Его надо удалять. Другой разработчик, увидев такой код, не будет знать что с ним делать. Почему его не удалили сразу? Можно ли его удалить? Это только отвлекает и захламляет кодовую базу.

https://github.com/DynamicSTOP/larapizza/blob/master/laravel/routes/api.php#L17
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/routes/channels.php#L16
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/routes/web.php#L39
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/database/seeds/DatabaseSeeder.php#L14
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Console/Kernel.php#L27
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Http/Kernel.php#L17
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Http/Kernel.php#L36
https://github.com/DynamicSTOP/larapizza/blob/master/laravel/app/Providers/AuthServiceProvider.php#L16

**Comment by DynamicSTOP** [comment]
![image](https://user-images.githubusercontent.com/9434504/174221891-dea49340-d8e0-49b6-acb8-d1e829516984.png)
